services:
  - type: web
    name: fb-auto-reply
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: FB_REDIRECT_URI
        sync: false
      - key: VERIFY_TOKEN
        generateValue: true
      - key: SECRET_KEY
        generateValue: true

  - type: postgres # <--- แก้ไขบรรทัดนี้
    name: fb-database
    plan: free
